web/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('password_change/', auth_views.PasswordChangeView.as_view(
    #     template_name='account/password_change.html'), name='password_change'),
    # path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(
    # template_name='account/password_change_done.html'), name='password_change_done'), 
    path('user_register/', views.user_register_page, name='register'),
    # path('user_register_idcheck/', views.user_register_idcheck, name='registeridcheck'),
    # path('user_register_res/', views.user_register_result, name='registerres'),
    # path('user_register_completed/', views.user_register_completed, 
    # name='registercompleted'),
    path('error/', views.error, name='error'),
    
]

web/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(),
    
]

web/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main,  name='main'),
]

web/account/models.py
from django.db import models

# Create your models here.

web/main/models.py
from django.db import models

# Create your models here.

web/account/views.py
from django.shortcuts import render

# Create your views here.

web/main/views.py
from django.shortcuts import render

# Create your views here.

web/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>방역</title>
</head>
<body>
    {% include 'header.html' %}
    
    {% block content %}
    {% endblock content %}
    
    {% block script %}
    {% endblock script %}
</body>
</html>

web/templates/error.html
<div>
    <div>
        <div>
            <span>404 Not Found</span>
            <div>페이지를 찾을 수 없습니다.</div>
            <a href="/main/">홈으로 돌아가기</a>
        </div>
    </div>
</div>

web/templates/header.html
<div id="header">
    <div class="logo">
        <div class="row">
            <div>
                <a href="{% url 'main:main' %}">MyWeb</a>
            </div>
            <div>
                {% if user.username %}
                    <a href="{% url 'account:password_change' %}">{{user.last_name}} 님 </a>
                    <a href="{% url 'account:logout' %}">로그아웃</a>
                {% else %}
                    <a href="{% url 'account:login' %}">로그인</a>
                    <a href="{% url 'account:register' %}">회원가입</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="menu">
        
    </div>
</div>

web/templates/main.html
{% extends 'base.html' %}

{% block content %}
<div>
    소통고리 코로나 방역 도우미
</div>
{% endblock content %}